import{S as u,i as d}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const p="42508369-6cc99fb978405cb8598a23b23",f="https://pixabay.com/api/",m="photo",h="horizontal",y=!0;function g(s){const t=encodeURIComponent(s),o=`${f}?key=${p}&q=${t}&image_type=${m}&orientation=${h}&safesearch=${y}`;return fetch(o).then(n=>{if(!n.ok)throw new Error("Image error");return n.json()}).catch(n=>{throw new Error("Error while fetching images from pixabay",n)})}function E(s,t){t.innerHTML="";const o=s.map(e=>` <div class="card">
         <a href="${e.webformatURL}"><img class="card-image" src="${e.webformatURL}" alt="${e.tags}" />
         <div class="card-info">
           <p>Likes: <span>${e.likes}</span></p>
           <p>Views: <span>${e.views}</span></p>
           <p>Comments: <span>${e.comments}</span></p>
           <p>Downloads:<span>${e.downloads}</span></p>
         </div></a>
       </div> `).join("");t.innerHTML=o,new u(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function c(s){d.error({title:"Error",message:s,position:"topRight"})}const L=document.querySelector("#search-form"),a=document.querySelector("#search-input"),b=document.querySelector(".gallery"),l=document.getElementById("loader");L.addEventListener("submit",function(s){s.preventDefault();const t=a.value.trim();if(t===""){c("Please fill imput");return}l.classList.remove("is-hidden"),g(t).then(o=>{if(o.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!");return}E(o.hits,b),a.value=""}).catch(o=>{console.error("Error during search:",o),c("Error")}).finally(()=>{l.classList.add("is-hidden")})});
//# sourceMappingURL=commonHelpers.js.map
